apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "invoicemanager.labels" . | nindent 4 }}
  annotations:
    # Bind this KSA to the GCP service account for Workload Identity
    iam.gke.io/gcp-service-account: {{ .Values.global.gcpAppSaEmail }}
